-- For Illegal Item Mode. To add to these lists, DM me.

_G.whitelist = {
    "0lsaaa",
    "BonfireDeveloper",
    "Bonamed",
    "Deniz_lxve99",
    "deniz_lxve99",
    "wSpooks",
    "Exturnaly",
    "thefireboy138",
    "Mudsslinger",
    "JumpingMar",
    "s2n_taz",
    "BonfireBot1",
    "DevinsFeelings",
    lp.Name,

    "alexxx720",
    "InxSpamrev",
    "Michaelgamer1454",
    "or_qq",
    "SylvesterMancini",
    "Player_UserBloxie",
    "ASHARTHEPROPLAYER",
    'hehyd3gbydy4yd',
    "Dreamin0fBlessins",
    "emilstycoonalt",
    "MMK_1903",
    "Baconforlife82971",
    "slqvrss",
    "uuaaddss",
    "TheDeep_M",
    "Gaming_0xo",
    "Blue_Applesauce1",
    "Abnormal_Results",
    "RobloxProGamer_Bro",
    "ed_kalwag555",
    "tealxn",
    "xxthebaconRealAltAcc",
    "oThreats",
    "HadiDas12",
    "Opzerium",
    "GODGAMER474",
    "14x0I",
    "riley_th33",
    "Quarexntxne",
    "buildman324",
    "dewbacktewelve",
    "carnagegrimssssi",
    "notcommandblock",
    "Kiehn43150",
    "birthday50153",
    "amproilikecake",
    "Eliasgamer566",
    "TrashAnomicPlayer",
    "Doninykas258",
    "DavidGamer73012",
    "FoxyFull_Dev",
    "mx1t",
    "WinFps",
    "StateOmnia",
    "handsome727",
    "EGHFHNJYTJHN",
    "GwoAiden",
    "Ksawereko1273",
    "James_Operational",
    "vxnlsh",
    "TheNobleFish",
    "ike_nine9",
    "yahelelcrack1",
    "ZulkZolnierz",
    "imgaret",
    "AlphonsoLerring",
    "LupinDev",
    "sapovolador",
    "CO0lpeke_Alt",
    "xJasonxxx1",
    "ah7md2down",
    "Gabetheman1293",
    "therobot890",
    "CodetheScripter",
    "TheBizzareGuyYT",
    "GoodPlayer_PL32",
    "goldfish380",
}

_G.blacklist = {
    "wst_g",
    "umboted17",
    "MMARC0Z",
}

_G.global_illegals = {
    "Health Booster"
}

_G.illegal_items = {
    "Kalashnikov",
    "Carbine",
    "Battle Rifle",
    "AR",
    "Shotgun",
    "Bullpup Shotgun",
    "Riot Shotgun",
    "Bullpup Rifle",
}
